on:
   push:
     branches:
       - master
jobs:
   test-install:
     name: Test Install
     strategy:
       matrix:
         distros: [ubuntu-latest]
     runs-on: ${{ matrix.distros }}
     steps:
       - uses: actions/checkout@v3
       - uses: Homebrew/actions/setup-homebrew@master
       - name: Install
         run: |
           bash install.sh << EOF
           pmqueiroz
           pedroqueiroz593@gmail.com
           password
           EOF
